import { generateText, stepCountIs, type LanguageModel, type ToolSet } from "ai";
import type { Bridge } from "../bridge.js";
import { CoordinationBroker, type CoordinationJob } from "../coordination/broker.js";
import { log } from "../log.js";
import type { ChatMessage } from "../types.js";
import { GoalGraph } from "./goals.js";
import { MemoryStore, verificationSchema, type AutonomousMemory } from "./memory.js";
import { AUTONOMOUS_COORDINATOR_PROMPT, AUTONOMOUS_WORKER_PROMPT } from "./prompts.js";
import { TrajectoryLog } from "./trajectory.js";

interface PlannedGoal { title:string; description?:string; priority?:number; dependsOnTitles?:string[]; companion?:string; verification?:unknown[] }
export interface AutonomousSupervisorOptions { key:string; workers?:number; continuationMs?:number; memoryRoot?:string; brokerRoot?:string }
export class AutonomousSupervisor {
  private readonly store:MemoryStore; private readonly trajectory:TrajectoryLog; private readonly broker:CoordinationBroker; private memory:AutonomousMemory; private graph:GoalGraph;
  private readonly workerCount:number; private coordinatorId=""; private disposed=false; private running=false; private timer:NodeJS.Timeout|null=null; private aborts=new Set<AbortController>();
  private readonly busyWorkers = new Set<string>();
  constructor(private readonly bridge:Bridge, private readonly model:LanguageModel, private readonly tools:ToolSet, opts:AutonomousSupervisorOptions){this.workerCount=Math.max(1,Math.min(4,opts.workers??3));this.store=new MemoryStore(opts.key,opts.memoryRoot);this.memory=this.store.load();this.graph=new GoalGraph(this.memory);this.broker=new CoordinationBroker(opts.key,opts.brokerRoot);this.trajectory=new TrajectoryLog(opts.key,opts.memoryRoot);this.schedule(opts.continuationMs??15_000);}
  async start():Promise<void>{this.coordinatorId=(await this.broker.registerAgent({name:"autonomous-coordinator",role:"coordinator",agentId:"autonomous-coordinator"})).id;for(let i=0;i<this.workerCount;i++){await this.broker.registerAgent({name:`local-worker-${i+1}`,role:"worker",agentId:`local-worker-${i+1}`});await this.bridge.call("spawn_companion",{name:["Ada","Babbage","Curie","Dijkstra"][i]}).catch(()=>{});}this.trajectory.append({type:"restart_recovery",data:{objective:this.memory.objective,workers:this.workerCount}});if(this.memory.objective&&!this.memory.paused)this.wake("restart");}
  onChat(msg:ChatMessage):void{if(msg.text.trim()==="!stop"){void this.emergencyStop();return;}this.memory.objectiveHistory.push({objective:msg.text,at:new Date().toISOString()});this.memory.objective=msg.text;this.memory.paused=false;this.memory.goals.filter(g=>!["done","failed"].includes(g.status)).forEach(g=>{g.status="failed";g.result="superseded by player instruction";});this.save();this.trajectory.append({type:"objective_change",tick:msg.tick,data:{player:msg.player,objective:msg.text}});this.wake("player_instruction");}
  onEvent(event:{tick:number;text:string}):void{this.trajectory.append({type:"game_event",tick:event.tick,data:{text:event.text}});this.wake("game_event");}
  dispose():void{this.disposed=true;if(this.timer)clearInterval(this.timer);for(const a of this.aborts)a.abort();this.save();}
  private schedule(ms:number):void{this.timer=setInterval(()=>{if(this.memory.objective&&!this.memory.paused)this.wake("continuation_timer");},Math.max(5_000,ms));}
  private wake(reason:string):void{if(this.running||this.disposed||this.memory.paused)return;this.running=true;void this.run(reason).catch(e=>log.error(`autonomous supervisor: ${e instanceof Error?e.message:e}`)).finally(()=>{this.running=false;});}
  private async run(reason:string):Promise<void>{this.trajectory.append({type:"supervisor_wake",data:{reason}});const events=await this.broker.takeCoordinationEvents(this.coordinatorId);for(const e of events){const goal=this.memory.goals.find(g=>g.id===e.jobId.replace(/^job-goal-/,"goal-"))??this.memory.goals.find(g=>g.title===e.title);if(!goal)continue;if(e.kind==="job_done"){goal.evidence.push(e.text);if(goal.verification.length===0){goal.status="done";goal.result=e.text;this.memory.recentAchievements.push(goal.title);}else{goal.status="blocked";goal.blockers=["deterministic verification data must be refreshed"];}this.trajectory.append({type:"worker_result",goalId:goal.id,jobId:e.jobId,data:{kind:e.kind,text:e.text}});}else if(e.kind==="job_failed"){goal.status=goal.attempts<2?"ready":"blocked";goal.blockers=goal.attempts<2?[]:[e.text];this.memory.failedApproaches.push(`${goal.title}: ${e.text}`);this.trajectory.append({type:"replanning",goalId:goal.id,data:{error:e.text}});}}
    this.graph.refresh();if(this.memory.goals.length===0||(!this.graph.ready().length&&!this.memory.goals.some(g=>g.status==="active"))){await this.plan();}await this.dispatch();this.save();}
  private async plan():Promise<void>{if(!this.memory.objective)return;const compact={objective:this.memory.objective,goals:this.memory.goals.map(g=>({title:g.title,status:g.status,blockers:g.blockers})),knownAreas:this.memory.knownAreas.slice(-8),failures:this.memory.failedApproaches.slice(-5)};const controller=new AbortController();this.aborts.add(controller);try{const result=await generateText({model:this.model,system:AUTONOMOUS_COORDINATOR_PROMPT,prompt:JSON.stringify(compact),abortSignal:controller.signal});const parsed=this.parsePlan(result.text);const created=new Map<string,string>();for(const p of parsed.goals.slice(0,3)){const verification=(p.verification??[]).map(v=>verificationSchema.parse(v));const g=this.graph.create({title:p.title,description:p.description,priority:p.priority,verification});created.set(p.title,g.id);}for(const p of parsed.goals){const id=created.get(p.title);if(id)for(const title of p.dependsOnTitles??[]){const dep=created.get(title)??this.memory.goals.find(g=>g.title===title)?.id;if(dep)this.graph.addDependency(id,dep);}}this.memory.decisions.push(parsed.decision??"planned next worker wave");this.trajectory.append({type:"coordinator_decision",data:{decision:parsed.decision,goals:parsed.goals.map(g=>g.title)}});}finally{this.aborts.delete(controller);}}
  private parsePlan(text:string):{goals:PlannedGoal[];decision?:string}{const match=text.match(/\{[\s\S]*\}/);if(!match)throw new Error("coordinator returned no JSON plan");const value=JSON.parse(match[0]) as {goals?:PlannedGoal[];decision?:string};if(!Array.isArray(value.goals))throw new Error("coordinator plan has no goals");return{goals:value.goals,decision:value.decision};}
  private async dispatch():Promise<void>{const snapshot=await this.broker.snapshot();const workers=snapshot.agents.filter(a=>a.role==="worker"&&!this.busyWorkers.has(a.id)).slice(0,this.workerCount);const ready=this.graph.ready().slice(0,workers.length);for(let i=0;i<ready.length;i++){const goal=ready[i]!;const worker=workers[i]!;this.busyWorkers.add(worker.id);goal.status="active";goal.attempts++;const [job]=await this.broker.submitJobs(this.coordinatorId,[{title:goal.title,instructions:goal.description,priority:goal.priority,companion:["Ada","Babbage","Curie","Dijkstra"][i],idempotencyKey:`${goal.id}:${goal.attempts}`}]);this.trajectory.append({type:"job_submitted",goalId:goal.id,jobId:job!.id});void this.runWorker(worker.id,job!,goal.id);}}
  private async runWorker(workerId:string,job:CoordinationJob,goalId:string):Promise<void>{let claimed:CoordinationJob|null=null;const companion=job.companion??"Ada";try{claimed=await this.broker.claimJob(workerId);if(!claimed)return;await this.broker.leaseCompanion(workerId,companion,600);this.trajectory.append({type:"worker_started",agentId:workerId,goalId,jobId:claimed.id});const controller=new AbortController();this.aborts.add(controller);try{const result=await generateText({model:this.model,system:AUTONOMOUS_WORKER_PROMPT,prompt:JSON.stringify({objective:claimed.instructions,companion,definitionOfDone:this.memory.goals.find(g=>g.id===goalId)?.verification,priorFailures:this.memory.failedApproaches.slice(-2)}),tools:this.tools,stopWhen:stepCountIs(15),abortSignal:controller.signal});await this.broker.finishJob(workerId,claimed.id,result.text||"worker completed tool loop");}finally{this.aborts.delete(controller);}}catch(error){if(claimed)await this.broker.failJob(workerId,claimed.id,error instanceof Error?error.message:String(error),false).catch(()=>{});}finally{await this.broker.releaseCompanion(workerId,companion).catch(()=>{});this.busyWorkers.delete(workerId);this.wake("worker_terminal");}}
  private async emergencyStop():Promise<void>{this.memory.paused=true;for(const a of this.aborts)a.abort();await this.bridge.call("cancel",{all:true}).catch(()=>{});await this.bridge.call("say",{text:"Stopped everything. Autonomous work is paused until a new instruction."}).catch(()=>{});this.trajectory.append({type:"emergency_stop"});this.save();}
  private save():void{this.store.save(this.memory);}
}
